AllCops:
  TargetRubyVersion: 2.7.4
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'frontend/**/*'
    - 'bin/*'

inherit_from: .rubocop_all.yml
require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-minitest

Layout/LineLength:
  Max: 240

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/BarePercentLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
